name: CI Page builder

on:
  push:
    branches:
        - main
env:
  USER_EMAIL: ${{ secrets.USER_EMAIL }}
  USER_NAME: ${{ secrets.USER_NAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Deploy
        uses: monstar-lab-oss/honkit-ghpages-action@main
